version: '3'
services:
    mongo:
      image: mongo
      container_name: mongodb
      ports:
        - "27017:27017"
    node-todo-api:
        image: stabarez/node-todo-api:master
        depends_on:
            - mongo
        links:
            - mongo
        ports:
            - "3000:3000"
